
"set runtimepath=~/vimrc/vim,~/vimrc/vim/after,\$VIMRUNTIME
"source ~/vimrc/vimrc
"helptags ~/vimrc/vim/doc






set nu
set autoindent

"pydiction 1.2 python auto complete
filetype plugin on
let g:pydiction_location = '~/.vim/tools/pydiction/complete-dict'
"defalut g:pydiction_menu_height == 15
"let g:pydiction_menu_height = 20 

filetype indent on
set smartindent
set smarttab
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

let Tlist_Inc_Winwidth=0
let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1

call pathogen#infect()
autocmd BufWritePost *.py call Flake8()
let g:flake8_ignore="E501" 
